services:

  mongodb:
    image: mongo:7
    container_name: blog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: blogdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog-network

  minio:
    image: minio/minio:latest
    container_name: blog-minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web d'administration
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: motdepasse123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - blog-network

  createbuckets:
    image: minio/mc:latest
    container_name: blog-minio-init
    depends_on:
      - minio
    networks:
      - blog-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set localminio http://minio:9000 admin motdepasse123;
      mc mb localminio/blog-images --ignore-existing;
      mc anonymous set download localminio/blog-images;
      exit 0;
      "

  backend:
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
    container_name: blog-backend-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/blogdb?authSource=admin
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: ""
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: motdepasse123
      MINIO_BUCKET: blog-images
      JWT_SECRET: cleSecreteTresLonguePourSignerLesTokensJWTMinimum256bits
      JWT_EXPIRATION: 86400000
    depends_on:
      - mongodb
      - minio
    networks:
      - blog-network

  frontend:
    build:
      context: .
      dockerfile: blog-frontend/Dockerfile
    container_name: blog-frontend-app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - blog-network

volumes:
  mongodb_data:
  minio_data:

networks:
  blog-network:
    driver: bridge