spring:
  application:
    name: blog-backend

  mongodb:
    uri: mongodb://admin:admin123@localhost:27017/blogdb?authSource=admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

minio:
  endpoint: http://localhost:9000        # utilisé par le backend pour parler à MinIO
  public-endpoint: http://localhost:9000  # utilisé pour les URLs renvoyées au navigateur
  access-key: admin
  secret-key: motdepasse123
  bucket: blog-images

jwt:
  secret: cleSecreteTresLonguePourSignerLesTokensJWTMinimum256bits
  expiration: 86400000 # 24h en millisecondes

logging:
  level:
    org.springframework.data.mongodb: DEBUG